name: bayesian-hmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.19.5
  - pandas=1.3.5
  - scipy>=1.5.0
  - pip
  - pip:
    - protobuf==3.20.3
    - tensorflow==1.15.0
    - tensorflow-probability==0.8.0