name: bayesian-tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.11.4
  - pip
  - pip:
    - tensorflow==2.11.0
    - tensorflow-probability==0.19.0